
document.querySelector(".one").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".one").innerHTML});
document.querySelector(".three").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".three").innerHTML});
document.querySelector(".four").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".four").innerHTML});
document.querySelector(".five").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".five").innerHTML});
document.querySelector(".six").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".six").innerHTML});
document.querySelector(".seven").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".seven").innerHTML});
document.querySelector(".eight").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".eight").innerHTML});
document.querySelector(".nine").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".nine").innerHTML});
document.querySelector(".zero").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".zero").innerHTML});
document.querySelector(".two").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".two").innerHTML});
document.querySelector(".opn").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".opn").innerHTML});
document.querySelector(".close").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".close").innerHTML});
document.querySelector(".minus").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".minus").innerHTML});
document.querySelector(".plus").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".plus").innerHTML});
document.querySelector(".dot").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".dot").innerHTML});
document.querySelector(".divide").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".divide").innerHTML});
document.querySelector(".clearall").addEventListener("click",function(){document.querySelector(".screen").innerHTML = "  "});
document.querySelector(".multiply").addEventListener("click",function(){document.querySelector(".screen").innerHTML += document.querySelector(".multiply").innerHTML});
document.querySelector(".equals").addEventListener("click",function(){
document.querySelector(".screen").innerHTML = eval(document.querySelector(".screen").innerHTML) });
document.querySelector(".delete").addEventListener("click", delt);
function delt() {
  var num1 = document.querySelector(".screen").innerHTML;
  var num2 = num1.length;
  var num4 = num2 - 1;
  var num3 = document.querySelector(".screen").innerHTML.slice(0, num4);
   document.querySelector(".screen").innerHTML = num3;
}
const body = document.querySelector("body");
const toggle = document.querySelector(".toggle");
const screen = document.querySelector(".screen");
const indicator = document.querySelector("#indicator");
const bod = document.querySelector(".body");
const clearall = document.querySelector(".clearall");
const dot = document.querySelector(".dot");
const divide = document.querySelector(".divide");
const del = document.querySelector(".delete");
const one = document.querySelector(".one");
const two = document.querySelector(".two");
const three = document.querySelector(".three");
const four = document.querySelector(".four");
const five = document.querySelector(".five");
const six = document.querySelector(".six");
const seven = document.querySelector(".seven");
const eight = document.querySelector(".eight");
const nine = document.querySelector(".nine");
const zero = document.querySelector(".zero");
const opn = document.querySelector(".opn");
const cls = document.querySelector(".close");
const minus = document.querySelector(".minus");
const plus = document.querySelector(".plus");
const equals = document.querySelector(".equals");
const multiply = document.querySelector(".multiply");

toggle.onclick = function(){body.classList.toggle("change");
screen.classList.toggle("change");
indicator.classList.toggle("change");
toggle.classList.toggle("change");
bod.classList.toggle("change");
clearall.classList.toggle("change");
dot.classList.toggle("change");
divide.classList.toggle("change");
del.classList.toggle("change");
one.classList.toggle("change");
two.classList.toggle("change");
three.classList.toggle("change");
four.classList.toggle("change");
five.classList.toggle("change");
six.classList.toggle("change");
seven.classList.toggle("change");
eight.classList.toggle("change");
nine.classList.toggle("change");
zero.classList.toggle("change");
opn.classList.toggle("change");
cls.classList.toggle("change");
minus.classList.toggle("change");
plus.classList.toggle("change");
equals.classList.toggle("change");
multiply.classList.toggle("change");
}
